[REACTBOIL-18] Update base font-size to use rem units in base 10
loopstudio/react-app-boilerplate23 pull request #11
Opened 2023-02-15 19:09 UTC by Tiago-Zarzavidjian

### :link: Board reference:

[Configurar root font size para usar rem units en base 10](https://loopstudio.atlassian.net/browse/REACTBOIL-18)

---

### :page_facing_up: Description

_This PR updates the base font size with the objective of using rem units in base 10, so that `1rem` equals `10px` (instead of 16px) without having to do complex conversions._

---

### :white_check_mark: Tasks:

- Configured `html` base `font-size`.
- Updated `Home` component font size.

---

### :pushpin: Notes:

- Note that this update will probably enforce the developers to use `rem` units for everything. If you mix `px` and `rem` you will get inconsistent results if the end user of the app sets the device size configuration to any value different from the default one.
- I added a `Global` styles component from `emotion`. We could probably add some global styles that are usually useful for most apps (like `height` for the root or ` text-rendering` config).

---

### :play_or_pause_button: Demo:

Demo of how a font of size set to `2rem` if effectively equal to `20px` (so `1rem` = `10px`)

https://www.loom.com/share/09898b6b7e4b4be298b9aedc60d7f01a

2023-02-15 19:18 UTC, FacuEM approved these changes

2023-02-15 20:05 UTC, gonchihernandez commented on src/features/Home/Home.styles.ts
>    margin-top: 20px;
could we use `rem` here instead of `px`?

2023-02-15 20:06 UTC, gonchihernandez requested changes
please change all the `px` units for `rem`

2023-02-17 16:40 UTC, gonchihernandez approved these changes
LGTM 🎖️

2023-02-23 12:14 UTC, glorio-loopstudio approved these changes
LGTM! 👍

2023-02-23 14:35 UTC, FacuEM approved these changes

2023-02-23 16:07 UTC, merged